Innovative Flix/force-app/main/default/objects/Season__c/Season__c.object-meta.xml
<CustomObject>
    <label>Season</label>
    <nameField>
        <displayFormat>S-{00000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Seasons</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

Innovative Flix/force-app/main/default/objects/Season__c/fields/Number__c.field-meta.xml
<CustomField>
    <fullName>Number__c</fullName>
    <label>Number</label>
    <precision>3</precision>
    <required>true</required>
    <scale>0</scale>
    <type>Number</type>
</CustomField>

Innovative Flix/force-app/main/default/objects/Season__c/fields/Tv_Serie__c.field-meta.xml
<CustomField>
    <fullName>Tv_Serie__c</fullName>
    <label>Tv Serie</label>
    <referenceTo>Tv_Serie__c</referenceTo>
    <relationshipLabel>Seasons</relationshipLabel>
    <relationshipName>Seasons</relationshipName>
    <relationshipOrder>0</relationshipOrder>
    <type>MasterDetail</type>
</CustomField>

Innovative Flix/force-app/main/default/objects/Tv_Serie__c/Tv_Serie__c.object-meta.xml
<CustomObject>
    <label>Tv Serie</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tv Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Innovative Flix/force-app/main/default/classes/SeasonTriggerHandlerTest.cls
@isTest
private with sharing class SeasonTriggerHandlerTest {
    @isTest static void checkDuplicateSeasonNumberTest() {

        Tv_Serie__c serie1 = TestDataFactory.getSerie('Test1', 'horror');
        insert serie1;

        Season__c season1 = TestDataFactory.getSeason(serie1, 1);
        Season__c season2 = TestDataFactory.getSeason(serie1, 2);
        Season__c season3 = TestDataFactory.getSeason(serie1, 2);
        insert season1;
        insert season2;

        Test.startTest();
        Database.SaveResult result = Database.insert(season3, false);
        Test.stopTest();    
    
        System.assertEquals('Season with this number already exists',
                             result.getErrors()[0].getMessage());

        
    }
    @isTest static void checkDuplicateSeasonNumberTest2() {

        Tv_Serie__c serie1 = TestDataFactory.getSerie('Test1', 'horror');
        insert serie1;

        Season__c season1 = TestDataFactory.getSeason(serie1, 1);
        Season__c season2 = TestDataFactory.getSeason(serie1, 2);
        Season__c season3 = TestDataFactory.getSeason(serie1, 3);
        insert season1;
        insert season2;
        insert season3;

        season3.Number__c = 2;

        Test.startTest();
        Database.SaveResult result = Database.update(season3, false);
        Test.stopTest();    
    
        System.assertEquals('Season with this number already exists',
                             result.getErrors()[0].getMessage());

        
    }

    @isTest static void checkDuplicateSeasonNumberTest3() {

        Tv_Serie__c serie1 = TestDataFactory.getSerie('Test1', 'horror');
        insert serie1;

        Season__c season1 = TestDataFactory.getSeason(serie1, 1);
        Season__c season2 = TestDataFactory.getSeason(serie1, 2);
        Season__c season3 = TestDataFactory.getSeason(serie1, 3);
        insert season1;
        insert season2;
        insert season3;

        season2.Number__c = 1;
        season3.Number__c = 2;

        Test.startTest();
        Database.SaveResult result1 = Database.update(season2, false);
        Database.SaveResult result2 = Database.update(season3, false);
        Test.stopTest();    
    
        System.assertEquals('Season with this number already exists',
                             result1.getErrors()[0].getMessage());

        System.assertEquals('Season with this number already exists',
                             result2.getErrors()[0].getMessage());
    }
    @isTest static void checkDuplicateSeasonNumberTest4() {

        Tv_Serie__c serie1 = TestDataFactory.getSerie('Test1', 'horror');
        insert serie1;

        Season__c season1 = TestDataFactory.getSeason(serie1, 1);
        Season__c season2 = TestDataFactory.getSeason(serie1, 2);
        Season__c season3 = TestDataFactory.getSeason(serie1, 1);
        Season__c season4 = TestDataFactory.getSeason(serie1, 2);
        insert season1;
        insert season2;

        Test.startTest();
        Database.SaveResult result1 = Database.insert(season3, false);
        Database.SaveResult result2 = Database.insert(season4, false);
        Test.stopTest();    
    
        System.assertEquals('Season with this number already exists',
                             result1.getErrors()[0].getMessage());
        System.assertEquals('Season with this number already exists',
                             result2.getErrors()[0].getMessage());

        
    }
}