Innovative Flix/force-app/main/default/objects/Tv_Serie__c/Tv_Serie__c.object-meta.xml
<CustomObject>
    <label>Tv Serie</label>
    <nameField>
        <displayFormat>{000}</displayFormat>
        <label>Name</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>Tv Series</pluralLabel>
    <sharingModel>ReadWrite</sharingModel>
</CustomObject>

Innovative Flix/force-app/main/default/objects/Tv_Serie__c/fields/Name__c.field-meta.xml
<CustomField>
    <fullName>Name__c</fullName>
    <label>Title</label>
    <length>255</length>
    <required>true</required>
    <type>Text</type>
    <unique>true</unique>
</CustomField>

Innovative Flix/force-app/main/default/classes/TvSerieTriggerHandler.cls
public with sharing class TvSerieTriggerHandler {
   public static void chcekDuplicateTVSerieTitle(List<Tv_Serie__c> newList) {

    List<Tv_Serie__c> oldList = [SELECT Id, Name__c FROM Tv_Serie__c];
        for(Tv_Serie__c newSerie : newList){
            for(Tv_Serie__c oldSerie : oldList) {
                if(newSerie.Name__c == oldSerie.Name__c)
                newSerie.addError('Tv Serie with this title already exists');
            }
        }



    }

}